//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuestionEntities : DbContext
    {
        private QuestionEntities()
             : base("name=QuestionEntities")
        {
        }

        private static QuestionEntities db;
        public static QuestionEntities getDbEntity()
        {
            if (db == null)
                db = new QuestionEntities();
            return db;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<UserContent> UserContents { get; set; }
        public virtual DbSet<UserQuestionOption> UserQuestionOptions { get; set; }
        public virtual DbSet<Userr> Userrs { get; set; }
        public virtual DbSet<Veto> Vetoes { get; set; }
    }
}
